version: '3.8'
services:
  database:
    image: postgres:13
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nestjs
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgresql_data:
    driver: local
  postgres:
